version: '3.9'

services:
  fixerror:
    image: ddc0330/terminal-fixer:latest   # 這裡改成你的 DockerHub image
    container_name: fixerror
    stdin_open: true
    tty: true
    volumes:
      - ./logs:/app/logs
      - fixerror-db:/app/db
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    entrypoint: ["python", "fixerror.py"]

volumes:
  fixerror-db:
